# Site information
idp_hostname: idp.example.org
idp_sp: https://sp.example.org

cert_hostname: "{{ idp_hostname }}"

letsencrypt_email: idp@example.org
letsencrypt_domain: "{{ idp_hostname }}"
letsencrypt_request_www: false
# apache is installed first and claims port 80. Pause it to allow LetsEncrypt to request a certificate
letsencrypt_pause_services: [apache2]

ssp_hostname: "{{ idp_hostname }}"
ssp_subject: "{{ cert_subject }}"
ssp_days_valid: "{{ cert_days_valid }}"
ssp_key: "{{ idp_hostname }}.pem"
ssp_certificate: "{{ idp_hostname }}.crt"
ssp_auth_admin_password: "changethispassword"
ssp_technicalcontact_name: Contact
ssp_technicalcontact_email: postmaster@{{ idp_hostname }}
ssp_managingcontact_name: Manager
ssp_managingcontact_email: webmaster@{{ idp_hostname }}
spp_sp_metadata: "{{ idp_sp }}/authentication/sp/metadata"
spp_sp_consumer: "{{ idp_sp }}/authentication/sp/consume-assertion"

ssl_hostname: "{{ idp_hostname }}"
ssl_webmaster: "webmaster@{{ ssl_hostname }}"
ssl_docroot: "{{ ssp_dir }}/www"
