# Site information
idp_hostname: idp.maes1.lab.surf.nl
idp_sp: https://sp.maes1.lab.surf.nl

cert_hostname: "{{ idp_hostname }}"

letsencrypt_email: "admin@{{ idp_hostname }}"
letsencrypt_domain: "{{ idp_hostname }}"
letsencrypt_request_www: false
# apache is installed first and claims port 80. Pause it to allow LetsEncrypt to request a certificate
letsencrypt_pause_services: [apache2]

ssp_version: 2.2.1
ssp_hostname: "{{ idp_hostname }}"
ssp_subject: "{{ cert_subject }}"
ssp_days_valid: "{{ cert_days_valid }}"
ssp_key: "{{ idp_hostname }}.pem"
ssp_certificate: "{{ idp_hostname }}.crt"
ssp_auth_admin_password: "changethispassword"
ssp_technicalcontact_name: Contact
ssp_technicalcontact_email: postmaster@{{ idp_hostname }}
spp_sp_metadata: "{{ idp_sp }}/authentication/sp/metadata"
spp_sp_consumer: "{{ idp_sp }}/authentication/sp/consume-assertion"
ssp_title_suffix: OpenConext-DIY2

ssl_hostname: "{{ idp_hostname }}"
ssl_webmaster: "webmaster@{{ ssl_hostname }}"
ssl_docroot: "{{ ssp_dir }}/public"
