---
- name: Ensure that packages are installed
  apt:
    name:
      - "libapache2-mod-php"
      - "php-date"
      - "php-json"
      - "php-xml"
      - "php-mbstring"
      - "php-curl"
      - "php-zip"
    state: "present"

- name: Enable apache PHP module
  shell: a2enmod php8.2

- name: Install SSP - Download archive
  get_url: url="{{ ssp_download_base_url }}/{{ ssp_tar_file }}" dest="{{ ssp_tar_location }}"
  register: ssp_download

- name: Install SSP - Unarchive it
  unarchive: src="{{ ssp_tar_location }}" dest="{{ ssp_installation_dir }}" copy=no

- name: Install SSP - Link dir to standard location
  file: path={{ ssp_dir }} src={{ ssp_unarchived_dir }} state=link force=true

- name: Create ssPHP logs directory
  file:
    path: "{{ ssp_dir }}/log"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Install SSP - Generate salt
  shell: /usr/bin/tr -c -d '0123456789abcdefghijklmnopqrstuvwxyz' </dev/urandom | /bin/dd bs=32 count=1 2>/dev/null;echo
  register: salt_command

- set_fact:
  args:
    ssp_secret_salt: "{{ salt_command.stdout }}"

- debug:
    msg: "Salt is {{ ssp_secret_salt }}"

- name: Ensure a self signed certificate is present
  command: openssl req -x509 -new -nodes -subj {{ ssp_subject }} -days {{ ssp_days_valid }} -out {{ ssp_dir }}/{{ ssp_cert_dir }}/{{ ssp_certificate }} -keyout {{ ssp_dir }}/{{ ssp_cert_dir }}/{{ ssp_key }}
  args:
    creates: "{{ ssp_dir }}/{{ ssp_cert_dir }}/{{ ssp_key }}"

- name: Install SSP - Remove unused config files and modules
  file: path="{{ item }}" state=absent
  with_items:
    - "{{ ssp_modules_dir }}/authorize"
    - "{{ ssp_modules_dir }}/consent"
    - "{{ ssp_modules_dir }}/consentAdmin"
    - "{{ ssp_modules_dir }}/discopower"
    - "{{ ssp_modules_dir }}/ldap"
    - "{{ ssp_modules_dir }}/metarefresh"
    - "{{ ssp_modules_dir }}/multiauth"
    - "{{ ssp_modules_dir }}/radius"
    - "{{ ssp_modules_dir }}/sqlauth"
    - "{{ ssp_modules_dir }}/statistics"
  notify:
    - restart apache

- name: Change ownership of self-signed certificate
  file:
    path: "{{ ssp_dir }}/{{ ssp_cert_dir }}/{{ ssp_key }}"
    owner: www-data

- name: Install SSP - Copy config and metadata
  template: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: "config/authsources.php.j2", dest: "{{ ssp_dir }}/config/authsources.php" }
    - { src: "config/config.php.j2", dest: "{{ ssp_dir }}/config/config.php" }
    - { src: "group_vars/logins.json", dest: "{{ ssp_well_known_logins }}" }
    - { src: "metadata/saml20-idp-hosted.php.j2", dest: "{{ ssp_dir }}/metadata/saml20-idp-hosted.php" }
    - { src: "metadata/saml20-idp-remote.php.j2", dest: "{{ ssp_dir }}/metadata/saml20-idp-remote.php" }
    - { src: "metadata/saml20-sp-remote.php.j2", dest: "{{ ssp_dir }}/metadata/saml20-sp-remote.php" }
  notify:
    - restart apache

- name: Install SSP - Enable example auth
  file: path="{{ ssp_modules_dir }}/exampleauth/enable" state=touch

