---
- include_vars: "packages.yml"
- include_vars: "repositories.yml"

# add the PPA key for the ondrej PHP version packages
- name: update key cache
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 4F4EA0AAE5267A6C
    state: present

- name: perform apt-get update
  apt:
    update_cache: yes
    cache_valid_time: 1
  become: Yes

- name: Ensure all necessary repositories are present
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items: "{{ repositories }}"
  become: Yes

- name: ensure that packages are installed
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages  }}"
  become: Yes

- name: Check if FQDN is resolvable
  command: dig @8.8.8.8 {{ idp_hostname }}
  register: dig

- set_fact:
  args:
    resolvable_fqdn: "{{ dig.stdout | search('.*HEADER.*NOERROR.*') }}"
